### ISSUE TITLE
Gradle error 

### ISSUE THREAD

**Issue by raviteja06** [yongjhih/RetroFacebook#37]
I tried to add v4 version of RetroFacebook to my project using
compile 'com.infstory:retrofacebook:1.0.1'

but when i am syncing project files its throwing couple of errors
1. Error:Failed to resolve: com.github.yongjhih:auto-json:unspecified
2. Error:Failed to resolve: com.github.yongjhih:retrofacebook-annotation:unspecified

am i missing anything?
Thanks in advance.

**Comment by yongjhih** [comment]
I'll verify that later for you.

**Comment by yongjhih** [comment]
Ok, I reproduced this issue, it's about missing uploaded packages. I will re-upload packages later

**Comment by yongjhih** [comment]
I re-uploaded packages. You can try the following build.gradle:

```
repositories {
    jcenter()
    maven {
        url "https://jitpack.io"
    }
    maven { // Remove this lines if some maven packages already been merged into jcenter() about 12hours.
        url 'https://dl.bintray.com/yongjhih/maven/'
    }
}

dependencies {
    compile 'com.infstory:retrofacebook:1.0.1' // v4
}
```

**Comment by JCollardBovy** [comment]
Hi yongjhih, i'm having the same issue as raviteja06 even after updating my build.gradle with the new configuration. I'm not sure if i'm missing something.

Could you provide us with a REALLY simple example project?

Thanks in advance

PD: I really liked your work and i'm eager to try it ;)

**Comment by yongjhih** [comment]
retrofacebook-app is a sample

**Comment by yongjhih** [comment]
My pleasure.

retrofacebook-app is a sample app though not simple. :)

You can try to add `--refresh-dependencies` option once:

```
./gradlew --refresh-dependencies clean assemble
```

Thanks.

**Comment by yongjhih** [comment]
Empty simple app: https://github.com/yongjhih/RetroFacebookSimpleApp

**Comment by raviteja06** [comment]
It works now. Thanks for the support.

I added below code synced projected with no errors
repositories {
    jcenter()
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.infstory:retrofacebook:1.0.1'
}

**Comment by yongjhih** [comment]
:+1:
